/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as WorkImiziRouteImport } from './routes/work.imizi'
import { Route as WorkRssbTigersRouteImport } from './routes/work.rssb-tigers'
import { Route as ApiPublicInquiryRouteImport } from './routes/api/public/inquiry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkImiziRoute = WorkImiziRouteImport.update({
  id: '/work/imizi',
  path: '/work/imizi',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRssbTigersRoute = WorkRssbTigersRouteImport.update({
  id: '/work/rssb-tigers',
  path: '/work/rssb-tigers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInquiryRoute = ApiPublicInquiryRouteImport.update({
  id: '/api/public/inquiry',
  path: '/api/public/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work/imizi': typeof WorkImiziRoute
  '/work/rssb-tigers': typeof WorkRssbTigersRoute
  '/api/public/inquiry': typeof ApiPublicInquiryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work/imizi': typeof WorkImiziRoute
  '/work/rssb-tigers': typeof WorkRssbTigersRoute
  '/api/public/inquiry': typeof ApiPublicInquiryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work/imizi': typeof WorkImiziRoute
  '/work/rssb-tigers': typeof WorkRssbTigersRoute
  '/api/public/inquiry': typeof ApiPublicInquiryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/work/$slug'
    | '/work/imizi'
    | '/work/rssb-tigers'
    | '/api/public/inquiry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/work/$slug'
    | '/work/imizi'
    | '/work/rssb-tigers'
    | '/api/public/inquiry'
  id:
    | '__root__'
    | '/'
    | '/work/$slug'
    | '/work/imizi'
    | '/work/rssb-tigers'
    | '/api/public/inquiry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkSlugRoute: typeof WorkSlugRoute
  WorkImiziRoute: typeof WorkImiziRoute
  WorkRssbTigersRoute: typeof WorkRssbTigersRoute
  ApiPublicInquiryRoute: typeof ApiPublicInquiryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/imizi': {
      id: '/work/imizi'
      path: '/work/imizi'
      fullPath: '/work/imizi'
      preLoaderRoute: typeof WorkImiziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/rssb-tigers': {
      id: '/work/rssb-tigers'
      path: '/work/rssb-tigers'
      fullPath: '/work/rssb-tigers'
      preLoaderRoute: typeof WorkRssbTigersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inquiry': {
      id: '/api/public/inquiry'
      path: '/api/public/inquiry'
      fullPath: '/api/public/inquiry'
      preLoaderRoute: typeof ApiPublicInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkSlugRoute: WorkSlugRoute,
  WorkImiziRoute: WorkImiziRoute,
  WorkRssbTigersRoute: WorkRssbTigersRoute,
  ApiPublicInquiryRoute: ApiPublicInquiryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
